import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

let a = 1;
let b = 2;
a == b;
console.log('a >= b', a >= b);

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="navbar">
                    <Link href="/">홈</Link>
                    <Link href="/list">리스트</Link>
                    <Link href="/abc/def">으악</Link>
                </div>
                {children}
            </body>
        </html>
    );
}
